prefixes = [
        ['dis', '반대 또는 부정'],
        ['un', '부정'],
        ['re', '다시, 반복'],
        ['pre', '미리, -전에'],
        ['mis', '잘못된, 부적절한'],
        ['sub', '아래, -부'],
        ['inter', '서로, 상호간'],
        ['semi', '반'],
        ['anti', '반대'],
        ['de', '아래로, 벗어나는 것'],
        ['trans', '-넘어서, 건너편'],
        ['super', '위, 초-'],
        ['under', '아래'],
        ['over', '넘치는, 초과'],
        ['ambi', '양쪽, 양측'],
        ['auto', '자동'],
        ['circum', '주위, 주변'],
        ['com', '함께, 공동'],
        ['con', '함께, 공동'],
        ['contra', '반대'],
        ['counter', '반대'],
        ['de', '없애다'],
        ['pre', '앞에'],
        ['pro', '앞에'],
        ['sub', '아래에'],
        ['super', '위에'],
        ['ab', '떨어져']
    ]
prefixes = sorted(prefixes, key=lambda x: len(x[0]), reverse=True)