#출처 : 서울교육청 어린이 교과서 필수 영단어
goodword = [
    "a", "about", "across", "act", "actor", "address", "afraid", "after", "afternoon", "again", "age", "ago", "air", "airplane", "airport",
    "album", "all", "along", "always", "among", "an", "and", "angry", "animal", "answer", "any", "apartment", "apple", "arm", "around",
    "arrive", "as", "ask", "at", "aunt", "autumn", "away", "baby", "back", "bad", "bag", "ball", "balloon", "banana", "band", "bank", "base",
    "basket", "bath", "be", "beach", "bear", "beautiful", "because", "become", "bed", "before", "begin", "behind", "bell", "below", "bench",
    "beside", "between", "bicycle", "big", "bird", "birthday", "black", "blank", "blow", "blue", "board", "boat", "body", "book", "bottle",
    "bowl", "box", "boy", "bread", "break", "breakfast", "bridge", "bright", "bring", "brother", "brown", "brush", "build", "burn", "burnt",
    "bus", "busy", "but", "butter", "button", "buy", "by", "bye", "cake", "calendar", "call", "camera", "camp", "can", "candle", "candy",
    "cap", "capital", "captain", "car", "card", "care", "carpenter", "carry", "cartoon", "case", "cassette", "cat", "catch", "ceiling", "center",
    "chair", "chalk", "chance", "change", "cheap", "cheese", "chicken", "child", "chopstick", "church", "circle", "city", "class", "classmate",
    "clean", "climb", "clock", "close", "clothes", "cloud", "club", "coat", "coffee", "coin", "cold", "color", "come", "comic book", "computer",
    "cook", "cool", "copy", "corner", "count", "country", "course", "cousin", "cover", "cow", "crayon", "cream", "cross", "cry", "cup", "curtain",
    "cut", "cute", "dad", "dance", "danger", "dark", "date", "daughter", "day", "dead", "deep", "deer", "desk", "dial", "diary", "dictionary",
    "die", "dinner", "dirty", "dish", "do", "doctor", "dog", "doll", "dollar", "dolphin", "door", "down", "draw", "dream", "dress", "drink",
    "drive", "drop", "drum", "dry", "duck", "ear", "early", "earth", "east", "echo", "empty", "end", "engine", "enjoy", "enough", "evening",
    "every", "example", "excellent", "excite", "excuse", "exercise", "eye", "face", "fact", "fair", "fall", "family", "famous", "far", "farm",
    "fast", "fat", "father", "feel", "few", "field", "fight", "fill", "film", "find", "fine", "finger", "finish", "fire", "fish", "fix", "flag",
    "floor", "flower", "fly", "follow", "food", "fool", "foot", "for", "forget", "fork", "free", "fresh", "friend", "from", "front", "fruit",
    "full", "fun", "game", "garden", "gas", "gate", "gentle", "get", "girl", "give", "glad", "glass", "glove", "go", "god", "gold", "good", "grandma",
    "grape", "grass", "gray", "great", "green", "ground", "group", "grow", "guitar", "hair", "half", "hall", "hamburger", "hand", "handle", "handsome",
    "happen", "happy", "hard", "hat", "hate", "have", "he", "head", "hear", "heart", "heavy", "hello", "help", "hen", "here", "hi", "hide", "high",
    "hiking", "hill", "hit", "hold", "hole", "holiday", "home", "hope", "horse", "hose", "hospital", "hot", "hotel", "hour", "house", "how", "hundred",
    "hungry", "hurry", "hurt", "ice", "idea", "if", "ill", "in", "ink", "interest", "into", "introduce", "island", "it", "jet", "job", "join", "juice",
    "jump", "jungle", "just", "keep", "key", "kick", "kid", "kill", "kind", "king", "kitchen", "knee", "knife", "knock", "know", "lady", "lake", "lamp",
    "land", "large", "last", "late", "laugh", "lead", "leaf", "learn", "leave", "left", "leg", "lesson", "let", "letter", "library", "lie", "light",
    "like", "line", "lion", "lip", "list", "listen", "long", "look", "lose", "lot", "loud", "love", "low", "luck", "lunch", "make", "man", "many", "map",
    "march", "market", "marry", "matter", "may", "meat", "medal", "meet", "melon", "meter", "middle", "milk", "million", "minute", "mirror", "Miss",
    "model", "mom", "money", "monkey", "month", "moon", "morning", "mother", "mountain", "mouth", "move", "movie", "Mr.", "Mrs.", "much", "music",
    "must", "neck", "need", "never", "new", "news", "next", "nice", "night", "no", "noise", "north", "nose", "not", "note", "now", "number", "nurse",
    "o'clock", "of", "off", "office", "often", "oh", "oil", "OK", "old", "on", "once", "open", "or", "orange", "other", "out", "over", "page", "paint",
    "pair", "pants", "paper", "pardon", "parent", "park", "party", "pass", "pay", "peace", "pear", "pen", "pencil", "people", "piano", "pick", "picnic",
    "picture", "piece", "pig", "pilot", "pin", "pine", "pink", "pipe", "place", "plan", "plane", "plant", "play", "please", "pocket", "point", "police",
    "pool", "poor", "post", "poster", "potato", "practice", "present", "pretty", "print", "problem", "pull", "push", "put", "queen", "question", "quick",
    "quiet", "radio", "rain", "rainbow", "read", "ready", "real", "record", "red", "remember", "repeat", "rest", "restaurant", "return", "ribbon", "rice",
    "rich", "ride", "right", "ring", "river", "road", "robot", "rock", "rocket", "roll", "roof", "room", "rose", "round", "ruler", "run", "same", "sand",
    "say", "school", "scissors", "score", "sea", "season", "seat", "see", "sell", "send", "service", "set", "shall", "shape", "she", "sheep", "sheet",
    "ship", "shirt", "shoe", "shoot", "shop", "short", "shoulder", "shout", "show", "shower", "shut", "sick", "side", "sight", "sign", "silver", "sing",
    "sir", "sister", "sit", "size", "skate", "skirt", "sky", "sleep", "slide", "slow", "smell", "smile", "smoke", "snow", "so", "soap", "soccer", "sock",
    "soft", "some", "son", "song", "soon", "sorry", "sound", "soup", "south", "space", "speak", "speed", "spell", "spend", "spoon", "sport", "spring",
    "square", "stair", "stamp", "stand", "star", "start", "station", "stay", "steam", "step", "stick", "stone", "stop", "store", "storm", "story",
    "stove", "straight", "strange", "strawberry", "street", "strike", "strong", "student", "study", "stupid", "subway", "sugar", "summer", "sun",
    "supermarket", "supper", "sure", "surprise", "sweater", "sweet", "swim", "swing", "switch", "table", "take", "talk", "tall", "tape", "taste", "taxi",
    "tea", "teach", "team", "telephone", "television", "tell", "temple", "tennis", "test", "than", "thank", "that", "the", "then", "there", "they",
    "thick", "thin", "thing", "think", "thirsty", "this", "thousand", "through", "throw", "thunder", "ticket", "tie", "tiger", "till", "time", "tired",
    "to", "today", "together", "tomato", "tomorrow", "tonight", "too", "tooth", "top", "touch", "town", "toy", "train", "travel", "tree", "trip", "truck",
    "true", "try", "tulip", "turn", "twice", "umbrella", "uncle", "under", "understand", "until", "up", "use", "usual", "vacation", "vegetable", "very",
    "video", "village", "violin", "visit", "wait", "wake", "walk", "wall", "want", "war", "warm", "wash", "waste", "watch", "water", "way", "we", "weak",
    "wear", "weather", "week", "welcome", "well", "west", "wet", "what", "when", "where", "which", "white", "who", "why", "wide", "will", "win", "wind",
    "window", "wing", "winter", "with", "woman", "wonder", "wood", "word", "work", "world", "write", "wrong", "Xmas", "xylophone", "yeah", "year",
    "yellow", "yes", "yesterday", "yet", "you", "young", "zero", "zoo"
]
